[workspace]

members = [
    "simple-whisper-cli",
    "simple-whisper-server",
    "simple-whisper"
]
resolver = "2"

[workspace.dependencies]
anyhow = "1.0.86"
axum = { version = "0.7.5", features = ["json", "ws"] }
clap = { version = "4.5.7", features = ["derive"] }
derive_builder = "0.20.0"
hf-hub = { version = "0.3.2", features = ["tokio"] }
indicatif = { version = "0.17.8", features = ["improved_unicode"] }
rodio = "0.18.1"
serde = "1.0.203"
serde_json = "1.0.117"
strum = { version = "0.26", features = ["derive"] }
tempfile = "3.10.1"
thiserror = "1.0.61"
tokio = { version = "1.38.0", features = ["full"] }
tower-http = { version = "0.5.2", features = ["trace"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }